
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Zeynep Nursena
 */
public class BedWindow extends javax.swing.JFrame {

    public BedWindow() {
        initComponents();
        date();
        times();
    }

    private void showPopUp(MouseEvent e) {
        popUp.show(this, e.getX(), e.getY());                                        // getX ve getY mouse a basılan noktanın koordinatlarını verir. 
                                                                                     //This ise popup ın görünür olacağı framedir.
    }

    public void date() {
        Date dt = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dd = sdf.format(dt);
        lbl_date.setText(dd);
    }

    Timer t;
    SimpleDateFormat st;

    public void times() {

        t = new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date dt = new Date();
                st = new SimpleDateFormat("hh:mm:ss a");
                String tt = st.format(dt);
                lbl_times.setText(tt);

            }
        });
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUp = new javax.swing.JPopupMenu();
        main = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        panel = new javax.swing.JPanel();
        btn_deleteSelected = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cb_bedType = new javax.swing.JComboBox<>();
        spinner_floor = new javax.swing.JSpinner();
        txt_dailyCost = new javax.swing.JTextField();
        btn_insertBed = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bedsTable = new javax.swing.JTable();
        lbl_png = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        lbl_times = new javax.swing.JLabel();
        rbtn_darkMode = new javax.swing.JRadioButton();

        main.setText("Back To Main Menu ");
        main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainActionPerformed(evt);
            }
        });
        popUp.add(main);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        popUp.add(exit);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelMouseReleased(evt);
            }
        });

        btn_deleteSelected.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btn_deleteSelected.setForeground(new java.awt.Color(35, 119, 166));
        btn_deleteSelected.setText("DELETE SELECTED");
        btn_deleteSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteSelectedActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(35, 119, 166));
        jLabel1.setText("Bed Type");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(35, 119, 166));
        jLabel2.setText("Floor");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(35, 119, 166));
        jLabel3.setText("Daily Cost");

        cb_bedType.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        cb_bedType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Extra Comfort" }));

        spinner_floor.setModel(new javax.swing.SpinnerNumberModel(0, -2, 10, 1));
        spinner_floor.setVerifyInputWhenFocusTarget(false);

        btn_insertBed.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btn_insertBed.setForeground(new java.awt.Color(35, 119, 166));
        btn_insertBed.setText("INSERT BED");
        btn_insertBed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertBedActionPerformed(evt);
            }
        });

        bedsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Bed Type", "Floor", "Cost"
            }
        ));
        jScrollPane1.setViewportView(bedsTable);

        lbl_png.setIcon(new javax.swing.ImageIcon(getClass().getResource("/acibadem_white_logo.jpg"))); // NOI18N

        lbl_date.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lbl_date.setForeground(java.awt.SystemColor.activeCaption);

        lbl_times.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lbl_times.setForeground(java.awt.SystemColor.activeCaption);

        rbtn_darkMode.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        rbtn_darkMode.setForeground(java.awt.SystemColor.activeCaption);
        rbtn_darkMode.setText("Dark Mode");
        rbtn_darkMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_darkModeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 977, Short.MAX_VALUE)
                            .addComponent(btn_deleteSelected, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btn_insertBed, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(34, 34, 34)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_dailyCost, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spinner_floor, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtn_darkMode)
                                    .addComponent(cb_bedType, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_date, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_times, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(118, 118, 118)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_png)))
                .addGap(19, 19, 19))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lbl_png, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(lbl_date, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(lbl_times, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(rbtn_darkMode)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cb_bedType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(spinner_floor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_dailyCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_deleteSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_insertBed))
                .addGap(34, 34, 34))
        );

        getContentPane().add(panel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_insertBedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertBedActionPerformed
        if (txt_dailyCost.getText().isEmpty() == false) {                                         //Eğer günlük ücret girildiyse if bloğu çalışır.
            try {
                float cost = Float.parseFloat(txt_dailyCost.getText());                           //Ücret string olarak girildiği için floata parse edilir.
                Database.RunCommand("INSERT INTO Bed(type,floor,cost) VALUES('" + cb_bedType.getSelectedItem().toString() + "'," + spinner_floor.getValue().toString() + "," + cost + ")");
                                                                                                  //INSERT ile database e veri ekliyoruz.                
                Database.ShowTable("SELECT id,floor,type,cost FROM Bed", new String[]{"#", "Floor", "Type", "Cost"}, bedsTable, 4);
                                                                                                  //SELECT ile bu eklenen verilen jtable'da gösteriyoruz.
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Invalid number");                            //Geçersiz herhangi bir şey girildiyse de catch bloğu çalışır ve geçersiz uyarısını verir. 
            }
        }

    }//GEN-LAST:event_btn_insertBedActionPerformed

    private void btn_deleteSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteSelectedActionPerformed
        try {
            int selection;                                                                       //int tipinde seçim adlı değişken tanımladım.
            selection = Integer.parseInt(bedsTable.getModel().getValueAt(bedsTable.getSelectedRow(), 0).toString()); 
                                                                                                 //bu değişkeni de framemimdeki table'dan çekiyorum.
                                                                                                 //Çektiğim değer integer tipinde olduğu için bununda toStringini alıyorum. 
            Database.RunCommand("DELETE FROM Bed WHERE id=" + selection);                        //Daha sonra database sınıfında yazmış olduğum RunCommand metodumu çağırıp
                                                                                                 //databasede bulunan bu selection ı siliyorum.
            Database.ShowTable("SELECT id,floor,type,cost FROM Bed", new String[]{"#", "Floor", "Type", "Cost"}, bedsTable, 4);
                                                                                                 //ShowTable metodumla da table'dan silinmesini istediğim değerin silindikten sonraki halini ekrana veriyorum.
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Please select a row");                          //Eğer herhangi bir seçim yapılmadıysa da catch bloğum çalışıyor ve lütfen bir satır seç uyarısı veriyor.
        }    }//GEN-LAST:event_btn_deleteSelectedActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();                                                                          //Penceredeki x işaretine basıldığında bütün framelerin değil de sadece tıkladığım framein
                                                                                                 //kapanmasını, diğer açılan framelerin kapanmamasını önlemek için de windowClosing'i kullandım.
    }//GEN-LAST:event_formWindowClosing

    private void mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainActionPerformed
        this.dispose();                                                                          //popup Menü ile bu frame kapanır 
        MainWindow mainWindow = new MainWindow();                                                // ve MainWindowdan mainWindow tekrar oluşturularak

        mainWindow.setVisible(true);                                                             //oluşturulan mainWindow görünür hale getirilir.
    }//GEN-LAST:event_mainActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.dispose();                                                                          //popUp menü ile frame kapatılır.
    }//GEN-LAST:event_exitActionPerformed

    private void panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMousePressed
        if (evt.isPopupTrigger()) {
            showPopUp(evt);                                                                       //mouse a basıldığında 
        }     }//GEN-LAST:event_panelMousePressed

    private void panelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseReleased
        if (evt.isPopupTrigger()) {
            showPopUp(evt);                                                                       //ve mouse bırakıldığına popup menü görünür olur.
        } 
    }//GEN-LAST:event_panelMouseReleased

    private void rbtn_darkModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_darkModeActionPerformed
        if (rbtn_darkMode.isSelected()) {                                                         //Eğer darkMode radiobutonu seçildiyse if bloğu çalışır.
            panel.setBackground(Color.BLACK);                                                     //Paneller siyah renge çevrilir.
            panel.setBackground(Color.BLACK);  
            btn_deleteSelected.setBackground(Color.GRAY);                                         //Butonlar gri renge çevrilir.
            btn_insertBed.setBackground(Color.GRAY);
            bedsTable.setBackground(Color.GRAY);
            ImageIcon icon = new ImageIcon("C:\\Users\\zeyne\\OneDrive\\Belgeler\\NetBeansProjects\\HospitalBedReservationSystem\\src\\acibadem_black_logo.png");
                                                                                                  //ACIBADEM yazısının backgroundunun orijinali beyaz olduğu için burda siyah versiyonunu kullandım.
            lbl_png.setIcon(icon); 
            txt_dailyCost.setBackground(Color.GRAY);
            cb_bedType.setBackground(Color.GRAY);

        } else { 
            panel.setBackground(Color.WHITE);                                                     //Eğer darkMode seçilmediyse else bloğu çalışır. Ve sistem framei eski moduna döner.
            btn_deleteSelected.setBackground(Color.WHITE);
            btn_insertBed.setBackground(Color.WHITE);
            bedsTable.setBackground(Color.WHITE);
            ImageIcon icon = new ImageIcon("C:\\Users\\zeyne\\OneDrive\\Belgeler\\NetBeansProjects\\HospitalBedReservationSystem\\src\\acibadem_white_logo.jpg");
            lbl_png.setIcon(icon);
            txt_dailyCost.setBackground(Color.WHITE);

        }    }//GEN-LAST:event_rbtn_darkModeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BedWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BedWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BedWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BedWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BedWindow().setVisible(true);
                try {
                    Database.Initialize();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bedsTable;
    private javax.swing.JButton btn_deleteSelected;
    private javax.swing.JButton btn_insertBed;
    private javax.swing.JComboBox<String> cb_bedType;
    private javax.swing.JMenuItem exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_png;
    private javax.swing.JLabel lbl_times;
    private javax.swing.JMenuItem main;
    private javax.swing.JPanel panel;
    private javax.swing.JPopupMenu popUp;
    private javax.swing.JRadioButton rbtn_darkMode;
    private javax.swing.JSpinner spinner_floor;
    private javax.swing.JTextField txt_dailyCost;
    // End of variables declaration//GEN-END:variables
}
