
import java.awt.Color;

/**
 *
 * @author Zeynep Nursena
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel = new javax.swing.JPanel();
        btn_manageBeds = new javax.swing.JButton();
        btn_managePatients = new javax.swing.JButton();
        btn_reservations = new javax.swing.JButton();
        btn_reports = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_backToSystem = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        rbtn_darkMode = new javax.swing.JRadioButtonMenuItem();
        rbtn_lightMode = new javax.swing.JRadioButtonMenuItem();
        menu_exit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panel.setBackground(new java.awt.Color(35, 119, 166));

        btn_manageBeds.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_manageBeds.setForeground(java.awt.SystemColor.activeCaption);
        btn_manageBeds.setText("MANAGE BEDS");
        btn_manageBeds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manageBedsActionPerformed(evt);
            }
        });

        btn_managePatients.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_managePatients.setForeground(java.awt.SystemColor.activeCaption);
        btn_managePatients.setText("MANAGE PATIENTS");
        btn_managePatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_managePatientsActionPerformed(evt);
            }
        });

        btn_reservations.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_reservations.setForeground(java.awt.SystemColor.activeCaption);
        btn_reservations.setText("RESERVATIONS");
        btn_reservations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reservationsActionPerformed(evt);
            }
        });

        btn_reports.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_reports.setForeground(java.awt.SystemColor.activeCaption);
        btn_reports.setText("REPORTS");
        btn_reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportsActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main_menu.gif"))); // NOI18N

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_managePatients, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_manageBeds, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_reservations, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_reports, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btn_manageBeds, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btn_managePatients, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btn_reservations, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btn_reports, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(panel);

        menu_backToSystem.setForeground(java.awt.SystemColor.activeCaption);
        menu_backToSystem.setText("BackToSystem");
        menu_backToSystem.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        menu_backToSystem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_backToSystemMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_backToSystem);

        jMenu1.setForeground(java.awt.SystemColor.activeCaption);
        jMenu1.setText("Mode");
        jMenu1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N

        buttonGroup1.add(rbtn_darkMode);
        rbtn_darkMode.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        rbtn_darkMode.setForeground(java.awt.SystemColor.activeCaption);
        rbtn_darkMode.setText("Dark Mode");
        rbtn_darkMode.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtn_darkModeStateChanged(evt);
            }
        });
        jMenu1.add(rbtn_darkMode);

        buttonGroup1.add(rbtn_lightMode);
        rbtn_lightMode.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        rbtn_lightMode.setForeground(java.awt.SystemColor.activeCaption);
        rbtn_lightMode.setText("Light Mode");
        rbtn_lightMode.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtn_lightModeStateChanged(evt);
            }
        });
        jMenu1.add(rbtn_lightMode);

        jMenuBar1.add(jMenu1);

        menu_exit.setForeground(java.awt.SystemColor.activeCaption);
        menu_exit.setText("Exit");
        menu_exit.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        menu_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_exitMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_exit);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_manageBedsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manageBedsActionPerformed
        try {
            this.dispose();                                                                //Açık olan frame kapanır.
            BedWindow bedWindow = new BedWindow();                                         //BedWindowdan bedWindow framei oluşturulup
            bedWindow.setVisible(true);                                                    //bu frame görünür hale getirilir.
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_manageBedsActionPerformed

    private void btn_managePatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_managePatientsActionPerformed
        try {
            this.dispose();                                                               //Açık olan frame kapanır.                                                
            PatientWindow patientWindow = new PatientWindow();                            //PaientWindowdan patientWindow framei oluşturulup
            patientWindow.setVisible(true);                                               //bu frame görünür hale getirilir.
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_managePatientsActionPerformed

    private void btn_reservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reservationsActionPerformed
        try {
            this.dispose();                                                              //Açık olan frame kapanır.        
            ReservationWindow reservationWindow = new ReservationWindow();               //ReservationWindowdan reservationWindow framei oluşturulup
            reservationWindow.setVisible(true);                                          //bu frame görünür hale getirilir.
        } catch (Exception ex) {
            ex.printStackTrace();
        }    }//GEN-LAST:event_btn_reservationsActionPerformed

    private void btn_reportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportsActionPerformed
        try {
            this.dispose();                                                              //Açık olan frame kapanır.        
            ReportsWindow reportsWindow = new ReportsWindow();                           //ReportsWindowdan reportsWindow framei oluşturulup
            reportsWindow.frame.setVisible(true);                                        //bu frame görünür hale getirilir.
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_reportsActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();                                                                  //Penceredeki x işaretine basıldığında bütün framelerin değil de sadece tıkladığım framein
                                                                                         //kapanmasını, diğer açılan framelerin kapanmamasını önlemek için de windowClosing'i kullandım.
    }//GEN-LAST:event_formWindowClosing

    private void menu_backToSystemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_backToSystemMouseClicked
        this.dispose();                                                                  //backToSystem menüsüne tıklandığında mainWindow framemi kapanır 
        System loginSystem = new System();                                               //ve Systeme geri dönülmesi için Systemden frame oluşturulur.
                                                                                         //ve bu frame görünür hale getirilir.
        loginSystem.setVisible(true);    }//GEN-LAST:event_menu_backToSystemMouseClicked

    private void menu_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_exitMouseClicked
        this.dispose();                                                                  //exit menüsüne tıklandığında frame kapanır ve program sonlanır.
    }//GEN-LAST:event_menu_exitMouseClicked

    private void rbtn_darkModeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtn_darkModeStateChanged
        if (rbtn_darkMode.isSelected()) {                                                //Eğer darkMode radio butonu seçildiyse if bloğu çalışır.
            panel.setBackground(Color.BLACK);                                            //Panel ve butonların backgroundı siyah renge set edilir.
            btn_manageBeds.setBackground(Color.BLACK);
            btn_managePatients.setBackground(Color.BLACK);
            btn_reports.setBackground(Color.BLACK);
            btn_reservations.setBackground(Color.BLACK);
        }
    }//GEN-LAST:event_rbtn_darkModeStateChanged

    private void rbtn_lightModeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtn_lightModeStateChanged
        if (rbtn_lightMode.isSelected()) {                                              //Eğer lightMode radio butonuna tıklandıysa 
            panel.setBackground(new Color(35, 119, 166));                               //Panel ve butonların rengi eski renklerine set edilir.
            btn_manageBeds.setBackground(Color.WHITE);
            btn_managePatients.setBackground(Color.WHITE);
            btn_reports.setBackground(Color.WHITE);
            btn_reservations.setBackground(Color.WHITE);

        }
    }//GEN-LAST:event_rbtn_lightModeStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
                try {
                    Database.Initialize();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_manageBeds;
    private javax.swing.JButton btn_managePatients;
    private javax.swing.JButton btn_reports;
    private javax.swing.JButton btn_reservations;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menu_backToSystem;
    private javax.swing.JMenu menu_exit;
    private javax.swing.JPanel panel;
    private javax.swing.JRadioButtonMenuItem rbtn_darkMode;
    private javax.swing.JRadioButtonMenuItem rbtn_lightMode;
    // End of variables declaration//GEN-END:variables
}
