
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Zeynep Nursena
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form RegisterWindow
     */
    public Register() {
        initComponents();
    }

    private void showPopUp(MouseEvent e) {                                                        
        popUp.show(this, e.getX(), e.getY());                                                           // getX ve getY mouse a basılan noktanın koordinatlarını verir. 
                                                                                                        //This ise popup ın görünür olacağı framedir.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUp = new javax.swing.JPopupMenu();
        loginSystem = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        lbl_password = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        btn_register = new javax.swing.JButton();
        txt_password = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();

        loginSystem.setText("Back To System");
        loginSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginSystemActionPerformed(evt);
            }
        });
        popUp.add(loginSystem);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Register", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 18), new java.awt.Color(35, 119, 166))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(704, 523));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });

        lbl_password.setBackground(new java.awt.Color(35, 119, 166));
        lbl_password.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lbl_password.setForeground(new java.awt.Color(35, 119, 166));
        lbl_password.setText("Password");

        btn_register.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_register.setForeground(new java.awt.Color(35, 119, 166));
        btn_register.setText("Register");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/acibadem_white_logo.jpg"))); // NOI18N

        lbl_username.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(35, 119, 166));
        lbl_username.setText("Username");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_password, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_username))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel4)))
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_register)
                .addGap(254, 254, 254))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_username)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_password)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(btn_register)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();                                                                                 //Penceredeki x işaretine basıldığında bütün framelerin değil de sadece tıkladığım framein
                                                                                                        //kapanmasını, diğer açılan framelerin kapanmamasını önlemek için de windowClosing'i kullandım. 
    }//GEN-LAST:event_formWindowClosing

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        if (txt_username.getText().isEmpty() == false && txt_password.getText().isEmpty() == false) {   //Eğer text alanı doluysa bu if bloğu çalışır.
            if (Database.Login(txt_username.getText(), txt_password.getText())) {                       //Database sınıfında oluşturduğum login metoduyla
                JOptionPane.showMessageDialog(null, "User already exists");                             //Daha önce böyle bir kullanıcı oluşturulmuş mu oluşturulmamış mı kontrol edilir
            } else {                                                                                    //Eğer önceden oluşturulmuşsa "bu kullanıcı zaten var" diye uyarı alınır.
                Database.RunCommand("INSERT INTO User VALUES('" + txt_username.getText() + "','" + txt_password.getText() + "')"); //Eğer daha önce oluşturulmadıysa Database sınıfında oluşturduğum
                JOptionPane.showMessageDialog(null, "Successfully registered");                        //RunCommand metodu ile database e bu kullanıcı kaydedilir. Ekrana başarıyla kaydolundu bilgisi gelir.
                this.dispose();                                                                        //Kaydolduktan sonra bu frame kapanacak ve system sayfasından artık login ile giriş yapılabilecek.
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please fill both fields.");                           //Eğer text alanlarından herhangi biri boş ise "lütfen iki alanı da doldurunuz" uyarısıyla karşılaşırız.
        }
    }//GEN-LAST:event_btn_registerActionPerformed

    private void loginSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginSystemActionPerformed
        this.dispose();                                                                                //Register framei kapanacak.
        System sys = new System();                                                                     //Systemden yeni bir sys oluşturup
        sys.setVisible(true);                                                                          //oluşturulan bu framei görünür yapıyorum.
                                                                                                       //register butonuyla login sayfasına direkt geçiş yapılıyor.
                                                                                                       //Bu popUp menuyu yapma amacım yanlışlıkla registere tıklandıysa
                                                                                                       //Systeme geri dönüş yapılabilecek olmasıdır.
                                                                                                      
    }//GEN-LAST:event_loginSystemActionPerformed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        if (evt.isPopupTrigger()) {                                                                    //mouse a basıldığında 
            showPopUp(evt);

        }    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
        if (evt.isPopupTrigger()) {                                                                    //ve mouse bırakıldığına popup menü görünür olur.
            showPopUp(evt);

        }    }//GEN-LAST:event_jPanel1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
                try {
                    Database.Initialize();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_register;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JMenuItem loginSystem;
    private javax.swing.JPopupMenu popUp;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
