
import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author Zeynep Nursena
 */
public class System extends javax.swing.JFrame {

    /**
     * Creates new form LoginP
     */
    public System() {
        initComponents();
        date();
        times();

    }

    public void date() {
        Date dt = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dd = sdf.format(dt);
        lbl_date.setText(dd);
    }

    Timer t;
    SimpleDateFormat st;

    public void times() {

        t = new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date dt = new Date();
                st = new SimpleDateFormat("hh:mm:ss a");
                String tt = st.format(dt);
                lbl_times.setText(tt);

            }
        });
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        panel = new javax.swing.JPanel();
        btn_register = new javax.swing.JButton();
        btn_login = new javax.swing.JButton();
        LOGIN = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_gif = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        lbl_times = new javax.swing.JLabel();
        rbtn_darkMode = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panel.setBackground(new java.awt.Color(255, 255, 255));

        btn_register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/manager_register_icon.png"))); // NOI18N
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });

        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/manager_login_icon.png"))); // NOI18N
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        LOGIN.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        LOGIN.setForeground(java.awt.SystemColor.activeCaption);
        LOGIN.setText("LOGIN");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel5.setForeground(java.awt.SystemColor.activeCaption);
        jLabel5.setText(" REGISTRATION");

        lbl_gif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/acibadem_white.gif"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel1.setForeground(java.awt.SystemColor.activeCaption);
        jLabel1.setText("HOSPITAL BED RESERVATION SYSTEM");

        lbl_date.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lbl_date.setForeground(java.awt.SystemColor.activeCaption);

        lbl_times.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lbl_times.setForeground(java.awt.SystemColor.activeCaption);

        rbtn_darkMode.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        rbtn_darkMode.setForeground(java.awt.SystemColor.activeCaption);
        rbtn_darkMode.setText("Dark Mode");
        rbtn_darkMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_darkModeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(LOGIN)
                        .addGap(351, 351, 351)
                        .addComponent(jLabel5)
                        .addGap(336, 336, 336))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154)
                        .addComponent(btn_register, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(283, 283, 283))))
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbl_times, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_gif)
                .addGap(46, 46, 46)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(jLabel1)
                .addContainerGap(361, Short.MAX_VALUE))
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbl_date, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbtn_darkMode)
                .addGap(15, 15, 15))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_date, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rbtn_darkMode)))
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                .addComponent(lbl_gif, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))))
                    .addComponent(lbl_times, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_register, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LOGIN)
                    .addComponent(jLabel5))
                .addGap(166, 166, 166))
        );

        getContentPane().add(panel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
       Login loginWindow = new Login();                                                    //Login ekranına geçilmesi için login sınıfından login frame i oluşturulur.
        loginWindow.setVisible(true);                                                      //setVisible ile oluşturulan login frame'i ekranda görünülür yapılır.
        this.dispose();

    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        Register registerWindow = new Register();                                          //Burada da aynı şekilde register ekranına geçilmesi için register sınıfından register frame i oluşturulur.
                                                                                           //Burada dispose yapmadım. Çünkü yeni kayıttan sonra mantıken sisteme giriş yapılacaktır.
                                                                                           //Sistem ekranı arkada açık kalacaktır.
        registerWindow.setVisible(true);                                                   //setVisible ile oluşturulan register frame'i ekranda görünür yapılır.
    }//GEN-LAST:event_btn_registerActionPerformed

    private void rbtn_darkModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_darkModeActionPerformed
        if (rbtn_darkMode.isSelected()) {                                                  //Eğer darkMode radiobutonu seçildiyse if bloğu çalışır.
            btn_login.setBackground(Color.BLACK);                                          //Butonlar siyah renge set edilir.
            btn_register.setBackground(Color.BLACK);
            ImageIcon icon = new ImageIcon("C:\\Users\\zeyne\\OneDrive\\Belgeler\\NetBeansProjects\\HospitalBedReservationSystem\\src\\acibadem_black.gif");
                                                                                           // //ACIBADEM gifinin backgroundunun orijinali beyaz olduğu için burda siyah versiyonunu kullandım.           
            lbl_gif.setIcon(icon);
            panel.setBackground(Color.BLACK);                                              //Paneller siyah renge set edilir.
        } else {
            btn_login.setBackground(Color.WHITE);                                          //Eğer darkMode radiobutonu seçilmediyse else bloğu çalışır
            btn_register.setBackground(Color.WHITE);                                       //Framemim ilk haline döner.
            ImageIcon icon = new ImageIcon("C:\\Users\\zeyne\\OneDrive\\Belgeler\\NetBeansProjects\\HospitalBedReservationSystem\\src\\acibadem_white.gif");
            lbl_gif.setIcon(icon);
            panel.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_rbtn_darkModeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new System().setVisible(true);
                try {
                    Database.Initialize();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOGIN;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_register;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_gif;
    private javax.swing.JLabel lbl_times;
    private javax.swing.JPanel panel;
    private javax.swing.JRadioButton rbtn_darkMode;
    // End of variables declaration//GEN-END:variables
}
